### ISSUE TITLE
Color ramp "native"

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/rialto-cesium#4]
Need to turn back on the color ramp "native", i.e. using R/G/B channels.

**Comment by mamayoleksandr** [comment]
Hi Michael,

sorry, just wondering, are there any chances native coloring will be implemented soon? We desperately need it. I have looked into the code, but am new with cesium, not sure if RGB data loaded form server at all.

thanks,

Alex.

**Comment by mamayoleksandr** [comment]
Hey Michael,

just fyi, added support for native coloring https://github.com/geosynergy/rialto-cesium/commit/2401ba1edfe49e6ca39addae0e0d05c6fb513729 , since all needed data already available in tile. 

thanks,

Alex.

**Comment by mpgerlek** [comment]
Excellent - I'd been meaning to turn that code back on for quite a while. 

If you submit a PR, I'll merge it in.

**Comment by mamayoleksandr** [comment]
done
https://github.com/radiantbluetechnologies/rialto-cesium/pull/7
